FROM ubuntu:22.04

WORKDIR /app

ENV DEBIAN_FRONTEND=noninteractive
ENV DATABASE_URL=postgresql://username:password@django-db/django_db

RUN apt-get update && \
    apt-get install -y python3 python3-pip postgresql-client libpq-dev libjpeg-dev iputils-ping && \
    apt-get clean

COPY . /app



RUN pip3 install --upgrade pip && \
    pip3 install --no-cache-dir psycopg2-binary && \
    pip3 install --no-cache-dir -r requirements.txt



EXPOSE 5000

CMD ["python3", "manage.py", "runserver"]


